[mypy]
warn_return_any = True
warn_unused_ignores = True
ignore_missing_imports = True
disallow_untyped_defs = True
check_untyped_defs = True

[mypy-mazegen.mlx.*]
ignore_errors = True

[mypy-mazegen.animator]
disable_error_code = attr-defined,no-any-return,has-type

[mypy-mazegen.tile_drawer]
disable_error_code = attr-defined,no-any-return

[mypy-mazegen.renderer]
disable_error_code = attr-defined
